export const FETCH_NEWS_START = 'FETCH_NEWS_START';
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_ERROR = 'FETCH_NEWS_ERROR';
export const TOGGLE_SORT_DIRECTION = 'TOGGLE_SORT_DIRECTION';
export const SET_SORT_COLUMN_DATA = 'SET_SORT_COLUMN_DATA';
